export const engineeringSuggestions = [
  "Civil Engineering",
  "Architectural Engineering",
  "Structural Engineering",
  "Building Inspection",
  "Interior Design",
  "Electrical Engineering",
  "HVAC Systems Design",
  "Plumbing Layouts",
  "Construction Management",
  "Site Survey",
  "AutoCAD Drafting",
  "Blueprint Analysis",
  "Landscape Architecture",
  "Urban Planning",
  "Masonry Inspection",
  "Foundation Design",
  "Bridge Design",
  "Roadway Design",
  "Project Estimation",
  "Steel Frame Design",
  "Reinforced Concrete Design",
  "Building Information Modeling (BIM)",
  "Permit Applications",
  "Safety Inspections",
  "Zoning Regulations",
  "Seismic Analysis",
  "Energy Efficiency Planning",
  "Lighting Design",
  "Electrical Circuit Design",
  "Roofing Plans",
  "Ventilation System Design",
  "Building Code Compliance",
  "Stormwater Management",
  "Geotechnical Engineering",
  "Sustainable Design",
  "Environmental Impact Assessment",
  "Urban Renewal",
  "Historic Preservation",
  "Water Resource Management",
  "Traffic Engineering",
  "Pavement Design",
  "Drainage Systems Design",
  "Construction Supervision",
  "Material Science",
  "Cost Estimation",
  "Project Scheduling",
  "Pile Foundation Design",
  "Tunnel Engineering",
  "Airport Design",
  "Port and Harbor Engineering",
  "Railway Engineering",
  "Pipeline Design",
  "Flood Risk Assessment",
  "Fire Safety Engineering",
  "Demolition Planning",
  "Retaining Wall Design",
  "Excavation Safety",
  "Shoring and Scaffolding",
  "Green Building Design",
  "Thermal Comfort Design",
  "Facade Engineering",
  "Urban Design",
  "Urban Mobility Planning",
  "Erosion Control",
  "Wind Load Analysis",
  "Tensile Structure Design",
  "Post-Tensioned Concrete Design",
  "Earthquake Resistant Design",
  "Slope Stability Analysis",
  "Rock Mechanics",
  "Waterproofing Systems Design",
  "Building Services Engineering",
  "Lighting Fixture Placement",
  "Mechanical Ventilation Design",
  "Acoustic Engineering",
  "Daylighting Design",
  "Energy Simulation",
  "Sewerage System Design",
  "Waste Management Systems",
  "Noise Control Engineering",
  "LEED Certification",
  "Geothermal System Design",
  "Thermal Insulation Design",
  "Rehabilitation Engineering",
  "Steel Structure Fabrication",
  "Traffic Signal Design",
  "Parking Lot Design",
  "Stormwater Pollution Prevention",
  "Traffic Flow Optimization",
  "Street Lighting Design",
  "Construction Claims Management",
  "Architectural Visualization",
  "Building Façade Inspection",
  "Smart Building Technologies",
  "Architectural 3D Modeling",
  "Construction Site Logistics",
  "Concrete Mix Design",
  "Air Quality Management",
  "Land Development Engineering",
  "Retrofitting",
  "Truss Design",
  "Load Bearing Wall Design",
  "Construction Health and Safety",
  "Integrated Project Delivery",
  "Prefabrication",
  "Utility Coordination",
  "Underground Utility Design",
  "Hazardous Material Assessment",
];
